
import config.koneksi;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class AwalKurangBahan extends javax.swing.JFrame {

    /**
     * Creates new form awalkurangBahan
     */
    public AwalKurangBahan() {
        initComponents();
        setLocationRelativeTo(this);
        warnatabel();
        tampil_tabel();
        setTitle("Pengurangan Bahan");
    }
    
    private void cari(){
        DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Kurang Bahan");
            model.addColumn("Tanggal");
            model.addColumn("Total Pengeluaran");
            
        try{
            Connection conn=(Connection)koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            String sql = "SELECT * FROM kurangbahan WHERE id_kubah LIKE '%"+txtcari.getText()+"%' OR tanggal LIKE '%"+txtcari.getText()+"%' OR total_pengeluaran LIKE '%"+txtcari.getText()+"%'";

            ResultSet res=stm.executeQuery(sql);  
            while(res.next()){
                model.addRow(new Object[]{
                   res.getString(1),
                   res.getString(2),
                   res.getString(3)              
               }); 
            }
            tabeldetailbahan.setModel(model);
        } catch (Exception e) {
        System.err.println(e.getMessage());
        }
    }
    
     public void tampil_tabel(){
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("ID Kurang Bahan");
        model.addColumn("Tanggal");
        model.addColumn("Total Pengeluaran");
        
        
        try {
            String sql = "SELECT * FROM kurangbahan";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                        res.getString(2), res.getString(3)
                        });
        }
            tabeldetailbahan.setModel(model);
        } catch (Exception e) {
            System.out.println("gagal tampil "+ e.getMessage());
        }
    }
     
     private void warnatabel(){
        DefaultTableCellRenderer headRender = new DefaultTableCellRenderer();
        headRender.setBackground(new Color(254,211,107));
        headRender.setForeground(new Color(255, 255, 255));
        headRender.setFont(new Font("Century Gothic", Font.BOLD, 18));
        tabeldetailbahan.getTableHeader().setDefaultRenderer(headRender);
        tabeldetailbahan.setRowHeight(30);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcari = new javax.swing.JTextField();
        txtidpengeluaranbahan = new javax.swing.JTextField();
        pilihtgl = new com.toedter.calendar.JDateChooser();
        btntambah = new javax.swing.JButton();
        btntambahbahan = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldetailbahan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(1152, 654));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcari.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtcari.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 129, 129), 3, true), "Cari Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 630, -1));

        txtidpengeluaranbahan.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtidpengeluaranbahan.setText("BK00");
        txtidpengeluaranbahan.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 129, 129), 3, true), "ID Pengurangan Bahan Baku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(txtidpengeluaranbahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 400, 60));

        pilihtgl.setBackground(new java.awt.Color(255, 246, 223));
        pilihtgl.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 129, 129), 3, true), "Tanggal"));
        pilihtgl.setDateFormatString("yyyy-M-dd");
        pilihtgl.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        getContentPane().add(pilihtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 400, 60));

        btntambah.setBackground(new java.awt.Color(254, 211, 107));
        btntambah.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btntambah.setForeground(new java.awt.Color(59, 61, 73));
        btntambah.setText("Tambah");
        btntambah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 129, 129), 3, true));
        btntambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntambahMouseExited(evt);
            }
        });
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 400, 50));

        btntambahbahan.setBackground(new java.awt.Color(255, 246, 223));
        btntambahbahan.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btntambahbahan.setForeground(new java.awt.Color(59, 61, 73));
        btntambahbahan.setText("Kurangi Stok Bahan");
        btntambahbahan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 129, 129), 3, true));
        btntambahbahan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntambahbahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntambahbahanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntambahbahanMouseExited(evt);
            }
        });
        btntambahbahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahbahanActionPerformed(evt);
            }
        });
        getContentPane().add(btntambahbahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 400, 50));

        btnkembali.setBackground(new java.awt.Color(255, 246, 223));
        btnkembali.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnkembali.setForeground(new java.awt.Color(59, 61, 73));
        btnkembali.setText("Kembali");
        btnkembali.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 129, 129), 3, true));
        btnkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkembaliMouseExited(evt);
            }
        });
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 400, 50));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 129, 129), 3, true), "Tabel Total Pengeluaran", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        tabeldetailbahan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tabeldetailbahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabeldetailbahan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabeldetailbahan.setSelectionBackground(new java.awt.Color(254, 242, 204));
        tabeldetailbahan.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tabeldetailbahan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 120, 630, 500));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("pengurangan stok bahan dari produksi hari ini");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 390, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Pengeluaran akan dihitung berdasarkan ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 390, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Hitung pengeluaran hari ini!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgdataadmin+.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, 654));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txtcariActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariKeyReleased

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(pilihtgl.getDate()));
        try {
            String sql  = "insert into kurangbahan (id_kubah, tanggal) values ('"+txtidpengeluaranbahan.getText()+"','"+tanggal+"')";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute(sql);
            JOptionPane.showMessageDialog(rootPane, "Data Telah Ditambahkan", "Pesan",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/tmp.png"));
            tampil_tabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btntambahbahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahbahanActionPerformed
        // TODO add your handling code here:
        KurangBahan kb = new KurangBahan();
        int baris = tabeldetailbahan.getSelectedRow();
        TableModel tm = tabeldetailbahan.getModel();

        String idkb = tm.getValueAt(baris, 0).toString();

        kb.txtidkurangbahan.setText(idkb);

        kb.setVisible(true);
        dispose();

    }//GEN-LAST:event_btntambahbahanActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        new PilihDB().setVisible(true);
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btntambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseEntered
        // TODO add your handling code here:
        btntambah.setBackground(new Color(185,147,54));
        btntambah.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btntambahMouseEntered

    private void btntambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseExited
        // TODO add your handling code here:
        btntambah.setBackground(new Color(254,211,107));
        btntambah.setForeground(new Color(59,61,73));
    }//GEN-LAST:event_btntambahMouseExited

    private void btntambahbahanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahbahanMouseExited
        // TODO add your handling code here:
        btntambahbahan.setBackground(new Color(225,225,225));
        btntambahbahan.setForeground(new Color(59,61,73));
    }//GEN-LAST:event_btntambahbahanMouseExited

    private void btntambahbahanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahbahanMouseEntered
        // TODO add your handling code here:
        btntambahbahan.setBackground(new Color(174,176,168));
        btntambahbahan.setForeground(new Color(59,61,73));
    }//GEN-LAST:event_btntambahbahanMouseEntered

    private void btnkembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseEntered
        // TODO add your handling code here:
        btnkembali.setBackground(new Color(174,176,168));
        btnkembali.setForeground(new Color(59,61,73));
    }//GEN-LAST:event_btnkembaliMouseEntered

    private void btnkembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseExited
        // TODO add your handling code here:
        btnkembali.setBackground(new Color(225,225,225));
        btnkembali.setForeground(new Color(59,61,73));
    }//GEN-LAST:event_btnkembaliMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AwalKurangBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AwalKurangBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AwalKurangBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AwalKurangBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AwalKurangBahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btntambahbahan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser pilihtgl;
    private javax.swing.JTable tabeldetailbahan;
    private javax.swing.JTextField txtcari;
    public javax.swing.JTextField txtidpengeluaranbahan;
    // End of variables declaration//GEN-END:variables
}
